version: "3.9"

services:
  mysql-buyer:
    image: mysql:8.0
    container_name: mysql-buyer
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: carbon_buyer
      
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - buyer-net

  buyer-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: buyer-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-buyer
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "8085:80"
    depends_on:
      - mysql-buyer
    networks:
      - buyer-net

  buyer-backend:
    build:
      context: ../../
      dockerfile: apps/buyer-backend-spring/Dockerfile
    container_name: buyer-backend
    restart: always

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-buyer:3306/carbon_buyer?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8081:8081"
    depends_on:
      - mysql-buyer
    networks:
      - buyer-net
    volumes:
      # Giúp Maven cache dependency (như admin backend)
      - ~/.m2:/root/.m2

networks:
  buyer-net:
    driver: bridge
