version: "3.9"

services:
  mysql-buyer:
    image: mysql:8.0
    container_name: mysql-buyer
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}

    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - buyer_mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ccm-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql-buyer
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      mysql-buyer:
        condition: service_healthy

volumes:
  buyer_mysql_data:
