spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ccm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:632005}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true # Handle existing tables gracefully
    schemas: ccm # Ensure correct schema is used
    validate-on-migrate: false # Skip checksum validation (useful in dev)

server:
  port: ${SERVER_PORT:8183}

logging:
  level:
    org.flywaydb: info
    org.hibernate.SQL: debug
app:
  security:
    jwt:
      secret: my-super-secret-key-for-jwt-minimum-32-characters-long-for-hs256
      expiration-ms: 900000
      refresh-expiration-ms: 604800000
