spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/carbon_admin}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:none}
    properties:
      "[hibernate.format_sql]": true
      "[hibernate.dialect]": ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
    open-in-view: false
  flyway:
    enabled: false
  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8082
  error:
    include-binding-errors: always
    include-message: always

app:
  security:
    mode: BASIC
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001
    dev-user:
      username: cva_officer
      password: password123
  audit:
    base-url: ${APP_AUDIT_BASE_URL:http://localhost:8080}
