spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccm?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 632005

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    clean-disabled: false
    locations: classpath:db/migration
    connect-retries: 10
app:
  security:
    jwt:
      secret: my-super-secret-key-for-jwt-minimum-32-characters-long-for-hs256
      expiration-ms: 900000
